### PR TITLE
Prepare new rc release: 9.3.4-rc4

### LINKED ISSUE #63: Update cppTango to latest 9.3-backports on next rc

### LINKED ISSUE #70: Update pogo on next rc release

### PR DESCRIPTION
**Pull request by t-b**
- [x] Merge cppTango PRs, https://github.com/tango-controls/cppTango/pull/690, https://github.com/tango-controls/cppTango/pull/689
- [x] Upgrade JTango version to something which includes https://github.com/tango-controls/JTango/pull/96
- [x] Merge https://github.com/tango-controls/cppTango/pull/672 (Edit the release date in the file)
- [x] Tag cppTango
- [x] Merge https://github.com/tango-controls/TangoSourceDistribution/pull/69
- [ ] Merge this PR
- [ ] Tag repo as `9.3.4-rc4`

Close #70 
Close #63

Release notes:

- [ ] 
> I was wondering whether we should add a reference to #61 issue somewhere too? (In the release > notes or in the warning message).

```markdown
Area | Release
-----|----------------------------------------------------------------
Updated C++ library to                   | 9.3.4-rc4
Updated Pogo to                            | 9.6.27

- Fix java version detection to only accept java 8 ([#64][pr-64])
- Default to `/usr` for omni automake checks ([#66][pr-66])
- Fix database connection test ([#65][pr-65])
- Warn on buggy mariadb client versions ([#69][pr-69])
```

### CODE REVIEW

**Comment by t-b** [comment]
Once we have a newer JTango version availbale, I think the "java must be version 8" check has to be revisited.

**Comment by bourtemb** [comment]
> 
> 
> Once we have a newer JTango version availbale, I think the "java must be version 8" check has to be revisited.

Still a problem with Pogo? 
https://github.com/tango-controls/pogo/issues/93

**Comment by t-b** [comment]
@bourtemb I would be in favour of finishing this PR like we have it know, release 9.3.4-rc4. And then move on to create the next rc. It feels not so productive to wait for every rc until everything is in place. Let's just do more rc releases and get integrated what is ready.

**Comment by bourtemb** [comment]
> @bourtemb I would be in favour of finishing this PR like we have it know, release 9.3.4-rc4. And then move on to create the next rc. It feels not so productive to wait for every rc until everything is in place. Let's just do more rc releases and get integrated what is ready.

@t-b, fine with me!

**Pull request merged**
