### PR TITLE
Prepare next rc

### LINKED ISSUE #52: Can not compile 9.3.3 on Debian
Hello,

for the record, It does not compile on Debian.

```
zmqeventsupplier.cpp:689:18: error: cannot convert 'zmq::socket_t' to 'void*'
  689 |     if (zmq_bind(*(ms.pub_socket),ms.endpoint.c_str()) != 0)
      |                  ^~~~~~~~~~~~~~~~
      |                  |
      |                  zmq::socket_t
In file included from /usr/include/zmq.hpp:38,
                 from ../../../lib/cpp/client/event.h:41,
                 from ./tango.h:146,
                 from zmqeventsupplier.cpp:33:
/usr/include/zmq.h:485:32: note:   initializing argument 1 of 'int zmq_bind(void*, const char*)'
  485 | ZMQ_EXPORT int zmq_bind (void *s_, const char *addr_);
      |                          ~~~~~~^~
```

you can find the full log here

https://salsa.debian.org/science-team/tango/-/jobs/290586

cheers

### PR DESCRIPTION
**Pull request by t-b**
Close #52.

### CODE REVIEW

**Comment by t-b** [comment]
@bourtemb FYI.

**Comment by t-b** [comment]
@bourtemb This should now be ready.

**Review by mliszcz — APPROVED** [review]
Looks good to me

**Review by bourtemb — APPROVED** [review]
Looks good to me too! Thanks!

**Review by Ingvord — APPROVED** [review]
Hmm... looks like we can add a var - VERSION to README and process it during assembling

**Pull request merged**
