### PR TITLE
Various build fixes

### PR DESCRIPTION
**Pull request by t-b**

### CODE REVIEW

**Comment by t-b** [comment]
@bourtemb Could you tag the starter repo to `Starter-7.3`? I'm not mighty enough to do that.

**Comment by t-b** [comment]
@mliszcz @bourtemb @Ingvord Ready for test and review.

**Comment by bourtemb** [comment]
Hi, bootstrap script was already present in the root directory and is already invoked when building.
So I would say, either we move the existing one to assets directory and update build.xml accordingly, or we stick with the current situation.

**Comment by Ingvord** [comment]
Do we need it in the distribution? Is it different from what we call in ant?

**Comment by t-b** [comment]
I did not find the existing bootstrap script. Mine is not different. I've removed mine.

**Comment by t-b** [comment]
@bourtemb @Ingvord @mliszcz Updated.

**Review by bourtemb — APPROVED** [review]
Looks good to me.
Before releasing 9.3.4-rc2, it looks like we'll have to create 9.3.4-rc2 tag in cppTango and to update distribution.properties accordingly to get the source distribution extracted under a directory named tango-9.3.4-rc2, unless I missed something?

**Comment by t-b** [comment]
@bourtemb I thought I had raised the versions already. Thanks for checking. Done now. cppTango is already tagged.

**Pull request merged**
