### PR TITLE
Add logback configuration file (fixes #21)

### LINKED ISSUE #21: add logback config file and adapt java appli startup scripts
Since tango 9.2.5a, some changes in JTango implied that now, by default, many debug messages are displayed when using the Tango java applications (jive, astor, ...).

I think we should add a logback default configuration file and update the Tango java applications startup scripts so they use this logback file.

At the ESRF, we have some startup scripts which are passing an option like that when starting the appli:
$JAVA -Dlogback.configurationFile=$LOG_BACK

With LOG_BACK variable pointing to our logback configuration file/
We should probably also provide a way to the user to use his own logback configuration file (if LOG_BACK environment variable is defined by the user for instance).

Here is the logback configuration file (I added .txt file extension to make github happy) we are using at the ESRF when starting on Linux:
[logback-linux.xml.txt](https://github.com/tango-controls/TangoSourceDistribution/files/3058947/logback-linux.xml.txt)

### PR DESCRIPTION
**Pull request by mliszcz**
This PR adds logback configuration (as proposed in #21).
I'll squash the commits after the review.

For now I have few concerns:
* I've used configuration file as provided by @bourtemb in #21. @bourtemb do you think we need ATTRIBUTE and SIFT appenders? Maybe we should just have CONSOLE one?
* I have not set `logback.configurationFile` for TangoRestServer. Logging seems to be handled by tomcat. @Ingvord do we need to change TangoRestServer configuration as well?
* The config is stored in `$PREFIX/share/java/`. I'm not convinced this is the best place. Maybe we should put in in `$PREFIX/share/tango/`. What do you think?

### CODE REVIEW

**Comment by Ingvord** [comment]
@mliszcz , when deployed as .jar TangoRestServer is an ordinary JTango server, hence external logback configuration will apply. Tomcat deals with logging when TangoRestServer is deployed as .war. TangoSourceDistribution has .jar. So I think setting logback configuration is a good idea, as it will provide coherent logging user experience

**Comment by bourtemb** [comment]
>     * I've used configuration file as provided by @bourtemb in #21. @bourtemb do you think we need ATTRIBUTE and SIFT appenders? Maybe we should just have CONSOLE one?

I have no idea. I am no Java expert and I don't know what these appenders are doing.
Maybe @gwen-soleil or @Ingvord have an answer to this question?

>     * The config is stored in `$PREFIX/share/java/`. I'm not convinced this is the best place. Maybe we should put in in `$PREFIX/share/tango/`. What do you think?

I don't have a strong opinion on that. Indeed, it might be better to isolate the tango stuff. So why not in `$PREFIX/share/tango`, indeed?

I would also rename the logback file from logback-linux.xml to logback.xml because when looking at it, it doesn't look like it is Linux specific (but I might be wrong).

**Comment by Ingvord** [comment]
@bourtemb, seems to me like something very Soleil specific. I attach logback we use at HZG
[logback.xml.txt](https://github.com/tango-controls/TangoSourceDistribution/files/3141387/logback.xml.txt)


> I would also rename the logback file from logback-linux.xml to logback.xml because when looking at it, it doesn't look like it is Linux specific (but I might be wrong).

+1

**Comment by bourtemb** [comment]
> @bourtemb, seems to me like something very Soleil specific. I attach logback we use at HZG
> [logback.xml.txt](https://github.com/tango-controls/TangoSourceDistribution/files/3141387/logback.xml.txt)

Indeed, this is a file we got from Soleil.
Thanks for your input and for the HZG logback file.

**Comment by mliszcz** [comment]
@Ingvord, @bourtemb thanks for your comments!

Today I spent some time reading logback docs and testing various configuration. Below are my observations based on TangoRestServer and jive behavior:

1. With ESRF's/Soleil's sifting appender:
    * there's a separate log file for each server instance, e.g.`$LOGS/TangoRestServer/rest.log`
    * apps are logging to `$LOGS/serverName_IS_UNDEFINED.log`
1. With HZG's sifting appender:
    * there's a separate log file for each device, e.g. `$LOGS/sys/rest/0.log`
    * apps are logging to `$LOGS/UNKNOWN_DEVICE_NAME.log`

I propose the following:
1. let's define two logback configuration files:
    * `$PREFIX/share/tango/logback.xml` - only console appender
    * `$PREFIX/share/tango/logback-server.xml` - console + file (sifting) appender
    * rationale: There is a common file for all applications and no PID is printed, so, at least with current format string, such log is useless. Also I don't think anyone could be interested in two-days old jive log.
1. let's put the logs into `${TANGO_LOG_PATH:-/var/log/tango}` (chmod to 777 as `var/log` is owned by root)
1. let's remove any facility-specific loggers, e.g. `fr.soleil.tango.parser` or `de.hzg.wpi`.
1. as for sifting appender and server logging, I need your help with to decide whether we shall follow ESFR's (per-server) or HZG's (per-device) approach. I do not have any real-world experience with large deployments (i.e. lots of servers and lots of devices).

**Comment by bourtemb** [comment]
> I propose the following:
> 
>     1. let's define two logback configuration files:
>        
>        * `$PREFIX/share/tango/logback.xml` - only console appender
>        * `$PREFIX/share/tango/logback-server.xml` - console + file (sifting) appender
>        * rationale: There is a common file for all applications and no PID is printed, so, at least with current format string, such log is useless. Also I don't think anyone could be interested in two-days old jive log.

Makes sense. But this means we would need 2 environment variables like LOGBACK to allow the users to override easily the 2 different default logback configurations.

>     2. let's put the logs into `${TANGO_LOG_PATH:-/var/log/tango}` (chmod to 777 as `var/log` is owned by root)

Default option will not necessary work for everybody since users are usually not allowed to create directories into /var/log. What about something in /tmp by default?

>     3. let's remove any facility-specific loggers, e.g. `fr.soleil.tango.parser` or `de.hzg.wpi`.

Makes sense.

>     4. as for sifting appender and server logging, I need your help with to decide whether we shall follow ESFR's (per-server) or HZG's (per-device) approach. I do not have any real-world experience with large deployments (i.e. lots of servers and lots of devices).

I don't have a strong opinion on this topic. @gwen-soleil, @ingvord, what do you think?
In any case, users will be able to override the default logback file. So I would go for any of the 2 options by default and let the users override the default using their own logback file if needed.

**Comment by mliszcz** [comment]
> Makes sense. But this means we would need 2 environment variables like LOGBACK to allow the users to override easily the 2 different default logback configurations.

Agree. We can have two vars (the former for apps and the latter for TangoRestServer):
```bash
LOGBACK=${TANGO_LOGBACK:-@prefix@/share/tango/logback.xml}
LOGBACK=${TANGO_LOGBACK_SERVER:-@prefix@/share/tango/logback-server.xml}
```


> Default option will not necessary work for everybody since users are usually not allowed to create directories into /var/log. What about something in /tmp by default?

`/tmp` is not guaranteed to be persistent across reboots. See: https://www.freedesktop.org/software/systemd/man/file-hierarchy.html. In this case I propose to use `/var/tmp/tango`. Permissions on Ubuntu 18.04:
```bash
$ ls -ld /var/tmp
drwxrwxrwt 8 root root 4096 maj  7 09:20 /var/tmp
```

> I don't have a strong opinion on this topic. @gwen-soleil, @Ingvord, what do you think?
In any case, users will be able to override the default logback file. So I would go for any of the 2 options by default and let the users override the default using their own logback file if needed.

I'm just wondering whether logging from outside of device scope (i.e. during server startup or from some factory) would be a problem with HZG approach (one .log file per device). Logs not associated with any device will go to `UNKNOWN_DEVICE_NAME.log`. In this case, either we would need users to specify different $LOG_HOME for each device server or we will end up with mixed logs.

Following does not work:
```xml
<appender name="FILE-${deviceName}" class="ch.qos.logback.core.rolling.RollingFileAppender">
    <file>${DEVICE_LOG_PATH}/${serverName}/${deviceName}.log</file>
```

`${serverName}` is resolved to `serverName_IS_UNDEFINED` even though ServerManager puts this property into MDC during `init()`:
https://github.com/tango-controls/JTango/blob/1ccc9dcb83e6de2359a9f1906d170571cacf1345/server/src/main/java/org/tango/server/ServerManager.java#L246-L247

**Comment by bourtemb** [comment]
> Agree. We can have two vars (the former for apps and the latter for TangoRestServer):
> 
> ```shell
> LOGBACK=${TANGO_LOGBACK:-@prefix@/share/tango/logback.xml}
> LOGBACK=${TANGO_LOGBACK_SERVER:-@prefix@/share/tango/logback-server.xml}
> ```

Seems fine to me.

> `/tmp` is not guaranteed to be persistent across reboots. See: https://www.freedesktop.org/software/systemd/man/file-hierarchy.html. In this case I propose to use `/var/tmp/tango`. Permissions on Ubuntu 18.04:
> 
> ```shell
> $ ls -ld /var/tmp
> drwxrwxrwt 8 root root 4096 maj  7 09:20 /var/tmp
> ```

I like /var/tmp/tango 

> I'm just wondering whether logging from outside of device scope (i.e. during server startup or from some factory) would be a problem with HZG approach (one .log file per device). Logs not associated with any device will go to `UNKNOWN_DEVICE_NAME.log`. In this case, either we would need users to specify different $LOG_HOME for each device server or we will end up with mixed logs.
> 
> Following does not work:
> 
> ```
> <appender name="FILE-${deviceName}" class="ch.qos.logback.core.rolling.RollingFileAppender">
>     <file>${DEVICE_LOG_PATH}/${serverName}/${deviceName}.log</file>
> ```
> 
> `${serverName}` is resolved to `serverName_IS_UNDEFINED` even though ServerManager puts this property into MDC during `init()`:
> https://github.com/tango-controls/JTango/blob/1ccc9dcb83e6de2359a9f1906d170571cacf1345/server/src/main/java/org/tango/server/ServerManager.java#L246-L247

So, you recommend to use ServerName_InstanceName approach (the one from Soleil) to ensure we have all the logs, even the ones which are not specific to a particular device?
I'm OK with that approach.

Thanks for the analysis.

**Comment by mliszcz** [comment]
> So, you recommend to use ServerName_InstanceName approach (the one from Soleil) to ensure we have all the logs, even the ones which are not specific to a particular device?

Yes, it's less surprising as one does not have specify custom logging path for each server.

I'll apply the changes as proposed in above discussion. @gwen-soleil, @Ingvord please let me know if you have any comments.

**Comment by Ingvord** [comment]
Fine with me.

**Comment by mliszcz** [comment]
I've squashed the commits. Please check.

Summary of changes:
* Env var TANGO_LOGBACK (default: $prefix/share/tango/logback.xml)
    * for all client applications (jive, etc. ...)
    * only console appender
* Env var TANGO_LOGBACK_SERVER (default: $prefix/share/tango/logback-server.xml)
    * currently only for TangoRestServer
    * console + file appender
    * Env var TANGO_JAVA_LOG_PATH (default: /var/log/tango/java)
    * logs are grouped per server, e.g. `/var/tmp/tango/java/TangoRestServer/rest.log`

**Review by bourtemb — APPROVED** [review]
Looks good to me.
I've done some simple tests, playing with the environment variables and it seems to work as expected.
I've seen default for TANGO_JAVA_LOG_PATH is /var/tmp/tango/java (as we agreed), not /var/log/tango/java as written in your last comment.

**Comment by mliszcz** [comment]
I have one more suggestion: maybe we should have env var for logging level, like in HZG's configuration:
```xml
<property name="log.level" value="${TANGO_JAVA_LOG_LEVEL:-INFO}"/>
```

So that one can easily increase verbosity when needed, e,g,:
```bash
TANGO_JAVA_LOG_LEVEL=DEBUG jive
```

What do you think?
Should we also have variable to control jacorb's verbosity?

**Comment by gwen-soleil** [comment]
No comments at all. Thanks a lot for the excellent job!

**Pull request merged**
