### PR TITLE
Fix zlib parameter

### LINKED ISSUE #88: zlib >= 1
configure requires zlib >= 1. Not sure when this has been introduced, but prevents to build on PPC legacy platforms (zlib 0.9)

### PR DESCRIPTION
**Pull request by t-b**
Close #88. I still don't see where we are using zlib, but in order to not break more, I've just resurrected the switch.

@lorenzopivetta The parameter `--without-zlib` is now available again. Does that solve the issue for you?

### CODE REVIEW

**Comment by lorenzopivetta** [comment]
@t-b Looks like the default won't use zlib, unless you specify --with-zlib at configuration. Is this the desired default? I think this will solve the issue, anyhow.

**Comment by t-b** [comment]
@lorenzopivetta The default is to use zlib. At least according to my testing and understanding.

**Comment by t-b** [comment]
@bourtemb Merge? After that I would then also merge #90.

**Review by bourtemb — APPROVED** [review]
Seems to work as expected.
DatabaseDS is linked by default with zlib (-lz) and is not linked with zlib when --without-lib is specified when running configure

**Pull request merged**
